The header and about section.
Uchenna-ibute/Portfolio pull request #1
Opened 2022-11-29 10:06 UTC by Uchenna-ibute

Addition of html file
Addition of css file
Addition of the linter 
Addition of the Readme

2022-11-29 12:21 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Uchenna-ibute , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media4.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/> |

## Highlights

- [ ] Good commit messages✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 12:21 UTC, joskalenda commented on README.md
> +  <h3><b>Microverse README Template</b></h3>
- [ ] Greate use of the readme template, please make sure you personalize it with your project details as title, description, and images.

2022-11-29 12:21 UTC, joskalenda commented on index.html
> +        </div>
- [ ] Well done on implementing this part, however, we are requested to use different Html tags, to say so, please change this div into a `ul` tag instead and wrap each `a` in a `li` accordingly

2022-11-29 12:21 UTC, joskalenda commented on index.html
> +    </section>
- [ ] This was a great idea to set the background image but I would suggest you download the whole image as one from the Figma template, these pieces make your code not clean and hard to manage and style.
- [ ] The images on lines 47 and 48 are broken, this is because you have misspelled them, `V12` instead of `v13`, please fix that too
> | image.   | 
> |-----------------|
> |  <img width="372" alt="im1" src="https://user-images.githubusercontent.com/77843050/204527261-1120f534-3483-4cd7-ab37-f95f01027446.png"> |

2022-11-29 12:21 UTC, joskalenda commented on style.css
> +}
- [OPTIONAL] As I said about multiple pieces of images, in the case where you used the whole image background as one, you should avoid repeating the same code again and again, this is not among coding best practices

2022-11-29 12:21 UTC, joskalenda commented on index.html
> +<body>
- [ ] Your efforts are to salute @Uchenna-ibute, you have done great progress, but let's take a look at this image below, seems like your design is not well aligned and styled as per the Figma design, please modify the changes comparing these 2 images

> | correct image    | wrong image |
> |-----------------|--------------|
> | <img width="311" alt="im4" src="https://user-images.githubusercontent.com/77843050/204524294-d7b96e64-3fd8-4c9e-bcbe-7bd31b06cc0f.png"> | <img width="427" alt="im2" src="https://user-images.githubusercontent.com/77843050/204524391-72c46642-7cb1-4093-850f-36d221307a1e.png"> |

- [ ] We can see the presence of some borders of the design, referring to the Figma design provided by microverse, we do not have them, please take a look at it and fix it as you will be submitting the second review.
- [ ] Your text font style is a bit different from the one on the Figma design, please pick and stick to the same properties used in the figma, you are requested to use the same, `padding, margin, color, fonts...` as per the Figma design

> | correct image    | wrong image |
> |-----------------|--------------|
> | <img width="311" alt="im4" src="https://user-images.githubusercontent.com/77843050/204524294-d7b96e64-3fd8-4c9e-bcbe-7bd31b06cc0f.png"> | <img width="384" alt="im3" src="https://user-images.githubusercontent.com/77843050/204525837-017c6f7d-1001-4ca0-aa94-8e6ffe51dcc4.png"> |

2022-11-29 14:36 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Uchenna-ibute , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media2.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif"/> |

## Highlights

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 14:36 UTC, joskalenda commented on index.html
> +            <img class="imgh" src="img/v13.png">
- [ ] Good work @Uchenna-ibute, you have corrected the image name as the previous reviewer(me) mentioned in the previous review, however, it is the only required change you have fixed in all those I gave, consider making all the changes as requested before you submit for your last review. Remember, according to the review policy, you can only submit 3times a PR, and this is your second one then consider making all the necessary required changes before you submit your last review, there you will have more chances not to result in a block repetition, we don't all need that. Please read again the previous review and fix them all. Good luck 🥰

2022-11-29 17:59 UTC, Abenezer-Tilahun commented on index.html
> +    </section>
Fixed.

2022-11-29 19:11 UTC, brainconnect93 requested changes
Hi @Uchenna-ibute,

Great work on making the changes requested by a previous reviewer 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966">

## Highlights
- Good use of GitHub flow 👌
- Linters set up well and passes  🟢
- Commit messages are descriptive and meaningful 🚀

## Required Changes ♻️
- Please try to stick to the Figma design for the font, colors, images, and spacing (margin/padding).
- Kindly use HTML semantic elements correctly.
- In General, Kindly make changes to what the previous reviewer as requested for. 
thanks.

_Check the comments under the review._

## Optional changes
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 19:11 UTC, brainconnect93 commented on index.html
> +        </div>
- [ ] Great to have worked on your project and you have inserted a lot of effort to get this far. According to the previous reviewer, he suggested you change this line of code in order to follow the [best HTML & CSS practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md). You can refactor the code.
Instead of what you have here:
``` CSS
<div class="icons">
   <a href="#"><i class="fa-brands fa-linkedin fas"></i></a>
   <a href="#"><i class="fa-brands fa-twitter fas"></i></a>
   <a href="#"><i class="fa-brands fa-github fas"></i></a>
   <a href="#"><i class="fa-brands fa-facebook fas"></i></a>
</div>
```
you can have it this way as suggested by the previous reviewer:

``` CSS
<ul class="icons">
   <li> <a href="#"><i class="fa-brands fa-linkedin fas"></i></a></li>
   <li><a href="#"><i class="fa-brands fa-twitter fas"></i></a></li>
   <li><a href="#"><i class="fa-brands fa-github fas"></i></a></li>
   <li><a href="#"><i class="fa-brands fa-facebook fas"></i></a></li>
</ul>
```

2022-11-29 19:11 UTC, brainconnect93 commented on index.html
> +<body>
- [ ] According to the previous reviewer, he made a request that you fix this alignment, and mobile version
you can easily fix this using the CSS responsiveness to fit the mobile version of the project. kindly check this [link](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design) to read more on CSS responsiveness.
From my end, the viewport still looks the same as what the previous reviewer pointed out: 👇 

![edit](https://user-images.githubusercontent.com/78634841/204621773-9ccb4c6f-bf2d-48f2-93c8-27597a941f09.png)

- Kindly fix it

2022-11-30 12:20 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @Uchenna-ibute   👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 12:30 UTC, merged