Creating the menu with javascript
Uchenna-ibute/Portfolio pull request #8
Opened 2022-12-20 09:15 UTC by Uchenna-ibute

Update the html and css file
Add the js file

2022-12-20 10:00 UTC, Owusu-Desmond requested changes
Hi @Uchenna-ibute and @danielmatama , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/xNJPkAQnLGVGjYpsBW/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅
:ping_pong: Good job :+1: to implement the functionality of the close and open of the mobile menu :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 10:00 UTC, Owusu-Desmond commented on index.html
> +                <span class="xmark"><i class="fa-solid fa-xmark"></i></span>
- [ ] Good job :+1: to implement the functionality of the close and open of the mobile menu, but from the project requirements, you should stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0), But as you can see there are some differences between the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0) and your design
  - Your menu close button does not show `@media screen` of `375px`
  - Your menu list item border bottom height does not match the Figma design
  
| Your Design |Figma Design |
| :---:   | :---: | 
| ![Screenshot from 2022-12-20 09-42-40](https://user-images.githubusercontent.com/92303891/208635854-995875a1-9e82-4d49-abec-a6098aa5ee39.png)| ![Screenshot from 2022-12-20 09-49-56](https://user-images.githubusercontent.com/92303891/208636842-c3183ec4-67a8-47b7-9496-412712d17812.png)|

2022-12-21 10:01 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Uchenna-ibute, and Team👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 10:01 UTC, thecodechaser commented on index.html
> +                <span class="xmark"><i class="fa-solid fa-xmark"></i></span>
- [ ] As requested by the previous reviewer, Please reduce the height(visibility) of the bottom border for mobile menu options.

### Your design

![image](https://user-images.githubusercontent.com/83803414/208877264-4e28852c-b029-438b-b0ea-10b8665275a0.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/208877420-340d11d9-2301-423e-ba67-1bbb414e7acd.png)

2022-12-21 15:38 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Uchenna-ibute, 

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://i.pinimg.com/originals/f8/3d/cf/f83dcf0c379de146ef962251952577ab.gif">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-21 15:41 UTC, merged